<!DOCTYPE html>
<html lang="en">
<head>

  @include('backend.common.head')
    
</head>
<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">
  <!-- Navbar -->
  @include('backend.common.navbar')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @include('backend.common.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1> Manage Menu</h1>
          </div>
          <div class="col-sm-6">
          @if (session('status'))
          <div class="alert alert-success" role="alert">
            <button type="button" class="close" data-dismiss="alert">×</button>
            {{ session('status') }}
          </div>
          @elseif(session('failed'))
          <div class="alert alert-danger" role="alert">
            <button type="button" class="close" data-dismiss="alert">×</button>
            {{ session('failed') }}
          </div>
          @endif
          </div> 
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row connectedSortable">
        <div class="col-md-6">


        <div class="card">
              <div class="card-header">
                <h3 class="card-title">Your Task</h3>
              </div>
              <!-- /.card-header -->
                <div class="card-body">

                  <div id="modules card-footer bg-light p-0">

                    
                    <ul class="nav nav-pills flex-column">
                      @foreach ($taskData as $tasklist)
                        <li class="nav-item drag" style="list-style-type: none; ">
                          <a href="#" id="dragItems" class="nav-link" style="color:gray;border: 1px solid gray;">
                          {{ $tasklist['taskname'] }}
                          <input type="hidden" name="dragItem" value="{{ $tasklist['id'] }}">
                          </a>
                        </li>
                      @endforeach
                    </ul>

                  </div>
                  
                </div>
            </div>

        </div>
        <div class="col-md-6">

            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Drag and Drop your task</h3>
              </div>
              <!-- /.card-header -->
                <div class="card-body">

                <div id="dropzone"></div>
                </div>

                  <div class="card-footer clearfix">
                    <input type="text" name="taskCategory" id="taskCategoryId" placeholder="Enter your task category name" required style="padding: 7px 50px 7px 7px;">
                    <button type="button" class="btn btn-primary float-right saveTaskButton" onclick="getDropItems();" style="padding: 7px 50px;"><i class="fas fa-plus"></i>Save</button>
                  </div>
                
            </div>

        </div>
        <!-- /.col-->
      </div>
      <!-- ./row -->

      <!-- ./row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  @include('backend.common.footer');

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

@include('backend.common.footer-bottom')

</body>
</html>



<script>
$('.drag').draggable({ 
  appendTo: 'body',
  helper: 'clone'
});

$('#dropzone').droppable({
  activeClass: 'active',
  hoverClass: 'hover',
  accept: ":not(.ui-sortable-helper)", // Reject clones generated by sortable

  drop: function (e, ui) {

    var inputValue = ui.draggable.find("input").val();

    console.log(inputValue);

    var $el = $('<div class="drag-items drop-item" >' + ui.draggable.text() + '</div>');

    $el.append($('<span style="display:none;">' + inputValue +  '</span>'));
    
    $el.append($('<button type="button" class="btn btn-default btn-xs remove"><i class="fas fa-trash-alt"></i></button>').click(function () { $(this).parent().detach(); }));
    $(this).append($el);

  }

}).sortable({

  items: '.drop-item',
  
  sort: function() {
    
    $(this).removeClass( "active" );
   
  }
});

function getDropItems()
{

    let container = document.getElementById("dropzone");

    let spans = container.getElementsByTagName("span");

    var inputCategoryVal = document.getElementById("taskCategoryId").value;

    let spansLengthCount = container.getElementsByTagName("span").length;

    //console.log(spansLengthCount);

    for (let span of spans) {
  
      let spanValue = span.textContent;

      console.log(spanValue);

      $.ajax({
            type:"POST",

            url:"/admin/saveTask",

            data: { 'id':spanValue, 'inputCategoryName':inputCategoryVal, 'countSpanTag':spansLengthCount,_token: '{{csrf_token()}}' },
            dataType: 'JSON',
            success:function(data){

              console.log('data');

            }
        });

    }

}


$(document).ready(function(){
    $('.saveTaskButton').attr('disabled',true);
    
    $('#taskCategoryId').keyup(function(){
        if($(this).val().length !=0){
            $('.saveTaskButton').attr('disabled', false);
        }
        else
        {
            $('.saveTaskButton').attr('disabled', true);        
        }
    })
});

</script>

<style>
  #modules {
  padding: 20px;
  background: #eee;
  margin-bottom: 20px;
  z-index: 1;
  border-radius: 10px;
}

#dropzone {
  padding: 20px;
  background: #eee;
  min-height: 100px;
  margin-bottom: 20px;
  z-index: 0;
  border-radius: 10px;
}

.active {
  outline: 1px solid red;
}

.hover {
  outline: 1px solid blue;
}

.drop-item {
  cursor: pointer;
  margin-bottom: 10px;
  background-color: rgb(255, 255, 255);
  padding: 5px 10px;
  border-radius: 3px;
  border: 1px solid rgb(204, 204, 204);
  position: relative;
}

.drop-item .remove {
  position: absolute;
  top: 4px;
  right: 4px;
}

.drag{
  color: #808080;
    background: white;
    padding: 10px;
}

.drag-items{
  color: #808080;
    background: #343a40;
    padding: 10px;
    margin-bottom: 10px;
}

.remove{
  float:right;
}

</style>
